/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_young_ffmpeg_player1_YoungPlayer */

#ifndef _Included_com_young_ffmpeg_player1_YoungPlayer
#define _Included_com_young_ffmpeg_player1_YoungPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     com_young_ffmpeg_player1_YoungPlayer
* Method:    initConfig
* Signature: (Ljava/lang/String;)V
*/
JNIEXPORT void JNICALL Java_com_example_ffmpeg_1test_jni_FFmpegJni_initConfig
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_young_ffmpeg_player1_YoungPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_young_ffmpeg_1player1_YoungPlayer_render
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_young_ffmpeg_player1_YoungPlayer
 * Method:    stopRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_young_ffmpeg_1player1_YoungPlayer_stopRender
        (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL
Java_com_young_ffmpeg_1player1_YoungPlayer_ffmpegInfo(JNIEnv *env, jobject clazz);

#ifdef __cplusplus
}
#endif
#endif
